const SET_DRAGGED_INDEX = 'SET_DRAGGED_INDEX';
const SET_DRAGGED_ITEM = 'SET_DRAGGED_ITEM';
const MOVE_DROPPABLE = 'MOVE_DROPPABLE';
const REORDER_DROPPABLE = 'REORDER_DROPPABLE';

export {
  SET_DRAGGED_INDEX,
  SET_DRAGGED_ITEM,
  MOVE_DROPPABLE,
  REORDER_DROPPABLE,
};
